services:
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  yt-broker:
    build:
      context: ../node-yt-helper
    container_name: yt-broker
    ports:
      - "3000:3000"
    volumes:
      - ../node-yt-helper:/usr/src/app
    restart: unless-stopped
    depends_on:
      - redis

volumes:
  redis_data:
