# Generated by Django 5.2.3 on 2025-08-27 15:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0015_optimize_unifiedsession_fields_and_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this search request', unique=True)),
                ('request_type', models.CharField(choices=[('video', 'Single Video'), ('playlist', 'Playlist'), ('topic', 'Topic Search')], help_text='Type of request: video, playlist, or topic search', max_length=20)),
                ('original_content', models.TextField(help_text='Original user input: URL for video/playlist requests, query for topic requests')),
                ('concepts', models.JSONField(blank=True, default=list, help_text='LLM-extracted concepts from user query (topic requests only)', null=True)),
                ('enhanced_queries', models.JSONField(blank=True, default=list, help_text='LLM-generated enhanced queries for search execution (topic requests only)', null=True)),
                ('intent_type', models.CharField(blank=True, choices=[('LOOKUP', 'Lookup'), ('TUTORIAL', 'Tutorial'), ('HOW_TO', 'How To'), ('REVIEW', 'Review')], help_text='LLM-classified intent of the user query (topic requests only)', max_length=20, null=True)),
                ('video_urls', models.JSONField(blank=True, default=list, help_text='List of YouTube video URLs found/processed')),
                ('total_videos', models.IntegerField(default=0, help_text='Total number of videos found/processed')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='processing', help_text='Current processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this search request was created')),
                ('unified_session', models.ForeignKey(help_text='Link to UnifiedSession for rate limiting and session management', on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='api.unifiedsession')),
            ],
            options={
                'verbose_name': 'Search Request',
                'verbose_name_plural': 'Search Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['search_id'], name='query_proce_search__e88226_idx'), models.Index(fields=['unified_session', 'created_at'], name='query_proce_unified_c9a17a_idx'), models.Index(fields=['status'], name='query_proce_status_958347_idx'), models.Index(fields=['request_type'], name='query_proce_request_b623c5_idx'), models.Index(fields=['created_at'], name='query_proce_created_e00dda_idx')],
            },
        ),
    ]
