# Generated by Django 5.2.3 on 2025-08-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_processor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='queryrequest',
            name='query_proce_search__e88226_idx',
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='concepts',
            field=models.JSONField(blank=True, default=list, help_text='LLM-extracted concepts from user query (topic requests only)'),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='enhanced_queries',
            field=models.JSONField(blank=True, default=list, help_text='LLM-generated enhanced queries for search execution (topic requests only)'),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='total_videos',
            field=models.PositiveIntegerField(default=0, help_text='Total number of videos found/processed'),
        ),
    ]
