# Generated by Django 5.2.3 on 2025-08-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_optimize_unifiedsession_fields_and_indexes'),
        ('query_processor', '0002_remove_queryrequest_query_proce_search__e88226_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryrequest',
            name='concepts',
            field=models.JSONField(blank=True, default=list, help_text='LLM-extracted concepts from user query (topic requests only)', null=True),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='enhanced_queries',
            field=models.JSONField(blank=True, default=list, help_text='LLM-generated enhanced queries for search execution (topic requests only)', null=True),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error details if status is failed', null=True),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('LOOKUP', 'Lookup'), ('TUTORIAL', 'Tutorial'), ('REVIEW', 'Review')], help_text='LLM-classified intent of the user query (topic requests only)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='queryrequest',
            name='request_type',
            field=models.CharField(choices=[('video', 'Video'), ('playlist', 'Playlist'), ('topic', 'Topic')], help_text='Type of request: video, playlist, or topic search', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='queryrequest',
            constraint=models.CheckConstraint(
                check=~models.Q(status='failed') | (
                    models.Q(error_message__isnull=False) & 
                    ~models.Q(error_message='')
                ),
                name='error_message_present_if_failed',
            ),
        ),
    ]
