# Generated by Django 5.2.3 on 2025-09-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_optimize_unifiedsession_fields_and_indexes'),
        ('query_processor', '0003_alter_queryrequest_concepts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queryrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Query Request', 'verbose_name_plural': 'Query Requests'},
        ),
        migrations.RemoveConstraint(
            model_name='queryrequest',
            name='error_message_present_if_failed',
        ),
        migrations.AddConstraint(
            model_name='queryrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'failed'), models.Q(('error_message__isnull', True), ('error_message', ''), _connector='OR'), _negated=True), name='error_message_present_if_failed'),
        ),
    ]
