# Generated by Django 5.2.3 on 2025-07-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLRequestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
