# Generated by Django 5.2.3 on 2025-07-10 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urlrequesttable_request_id'),
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrequesttable',
            name='search_request',
            field=models.ForeignKey(blank=True, help_text='Link to the search request that generated this URL', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_requests', to='topic.searchrequest'),
        ),
    ]
