# Generated by Django 5.2.3 on 2025-07-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_urlrequesttable_search_request'),
    ]

    operations = [
        # Add index on URLRequestTable.search_request for efficient reverse lookups
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(
                fields=['search_request'],
                name='search_request_idx'
            ),
        ),
    ]