# Generated by Django 5.2.3 on 2025-07-10 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_search_request_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='urlrequesttable',
            name='search_request_idx',
        ),
    ]
