# Generated by Django 5.2.4 on 2025-07-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_urlrequesttable_search_request_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrequesttable',
            name='celery_task_id',
            field=models.CharField(blank=True, help_text='ID of the main Celery task processing this video', max_length=255, null=True),
        ),
    ]
