# Generated by Django 5.2.3 on 2025-07-19 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_urlrequesttable_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlrequesttable',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('failed_permanently', 'Failed Permanently'), ('success', 'Success')], default='processing', max_length=20),
        ),
    ]
