# Generated by Django 5.2.3 on 2025-07-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_convert_failed_permanently_to_failed'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrequesttable',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('excluded', 'Excluded'), ('no_transcript', 'No Transcript'), ('no_metadata', 'No Metadata'), ('technical_failure', 'Technical Failure')], help_text='Reason why the video processing failed', max_length=20, null=True),
        ),
    ]
