# Generated by Django 5.2.3 on 2025-07-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_failure_reason_field'),
        ('topic', '0003_add_video_exclusion_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlrequesttable',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(fields=['status'], name='api_urlrequ_status_05e00f_idx'),
        ),
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(fields=['failure_reason'], name='api_urlrequ_failure_dfbe78_idx'),
        ),
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(fields=['created_at'], name='api_urlrequ_created_0b60df_idx'),
        ),
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(fields=['status', 'created_at'], name='api_urlrequ_status_16621e_idx'),
        ),
        migrations.AddIndex(
            model_name='urlrequesttable',
            index=models.Index(fields=['status', 'failure_reason'], name='api_urlrequ_status_3ac584_idx'),
        ),
    ]
