# Generated by Django 5.2.3 on 2025-07-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_urlrequest_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlrequesttable',
            name='chain_task_id',
            field=models.CharField(blank=True, help_text='ID of the Celery chain task for result tracking', max_length=255, null=True),
        ),
    ]
