# Generated by Django 5.2.3 on 2025-08-16 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_chain_task_id_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlrequesttable',
            name='id',
        ),
        migrations.AlterField(
            model_name='urlrequesttable',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
