# Generated by Django 5.2.3 on 2025-08-25 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_make_request_id_primary_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_ip', models.GenericIPAddressField(db_index=True)),
                ('video_requests', models.IntegerField(default=0, help_text='Number of single video processing requests')),
                ('playlist_requests', models.IntegerField(default=0, help_text='Number of playlist processing requests')),
                ('topic_requests', models.IntegerField(default=0, help_text='Number of topic search requests')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
                ('user_account', models.ForeignKey(blank=True, help_text='Associated user account (null for anonymous sessions)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_request_at'],
                'indexes': [models.Index(fields=['user_ip'], name='api_unified_user_ip_5f113b_idx'), models.Index(fields=['session_id'], name='api_unified_session_7aa5ed_idx'), models.Index(fields=['created_at'], name='api_unified_created_8b4016_idx'), models.Index(fields=['last_request_at'], name='api_unified_last_re_b71cb2_idx')],
            },
        ),
    ]
