# Generated by Django 5.2.3 on 2025-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_unifiedsession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='unifiedsession',
            name='api_unified_session_7aa5ed_idx',
        ),
        migrations.AlterField(
            model_name='unifiedsession',
            name='playlist_requests',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of playlist processing requests'),
        ),
        migrations.AlterField(
            model_name='unifiedsession',
            name='topic_requests',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of topic search requests'),
        ),
        migrations.AlterField(
            model_name='unifiedsession',
            name='user_ip',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='unifiedsession',
            name='video_requests',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of single video processing requests'),
        ),
    ]
