# Generated by Django 5.2.3 on 2025-09-07 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsresult',
            name='video_id',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video ID format', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
        migrations.AlterField(
            model_name='metadataresult',
            name='video_id',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video ID format', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
        migrations.AlterField(
            model_name='transcriptresult',
            name='video_id',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video ID format', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
        migrations.AlterField(
            model_name='videotable',
            name='video_id',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Invalid YouTube video ID format', regex='^[A-Za-z0-9_-]{11}$')]),
        ),
    ]
