# Generated by Django 5.2.3 on 2025-10-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_workflow', '0003_transcriptsegment_delete_transcriptresult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotable',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text='List of detected chapters with timestamps'),
        ),
    ]
