# Generated by Django 5.2.3 on 2025-10-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yt_workflow', '0004_videotable_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotable',
            name='executive_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Executive summary with key highlights'),
        ),
    ]
