# Generated by Django 5.2.3 on 2025-07-02 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_urlrequesttable_request_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('view_count', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_metadata', to='api.urlrequesttable')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField()),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='video_transcript', to='api.urlrequesttable')),
            ],
        ),
    ]
