# Generated by Django 5.2.3 on 2025-07-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=20),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=20),
        ),
    ]
