# Generated by Django 5.2.3 on 2025-07-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0004_auto_20250703_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='video_id',
            field=models.CharField(blank=True, db_index=True, help_text="YouTube video ID (e.g., 'dQw4w9WgXcQ')", max_length=20, null=True, unique=True),
        ),
    ]
