# Generated by Django 5.2.3 on 2025-07-04 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urlrequesttable_request_id'),
        ('video_processor', '0005_add_video_id_to_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='video_metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_transcript', to='video_processor.videometadata'),
        ),
        migrations.AlterField(
            model_name='videotranscript',
            name='url_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_transcript_old', to='api.urlrequesttable'),
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_id', models.CharField(db_index=True, help_text="Unique segment ID format: 'video_id_segment_number' (e.g., 'dQw4w9WgXcQ_001')", max_length=50, unique=True)),
                ('sequence_number', models.IntegerField(help_text='Sequential order of this segment in the video')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('end_time', models.FloatField(help_text='End time in seconds')),
                ('duration', models.FloatField(help_text='Duration of this segment in seconds')),
                ('text', models.TextField(help_text='Text content of this segment')),
                ('is_embedded', models.BooleanField(default=False, help_text='Whether this segment has been embedded in vector store')),
                ('embedding_vector_id', models.CharField(blank=True, help_text='Vector store ID (usually same as segment_id)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='video_processor.videotranscript')),
            ],
            options={
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['transcript', 'sequence_number'], name='video_proce_transcr_49339c_idx'), models.Index(fields=['start_time'], name='video_proce_start_t_a6b37c_idx'), models.Index(fields=['is_embedded'], name='video_proce_is_embe_37866e_idx')],
                'unique_together': {('transcript', 'sequence_number')},
            },
        ),
    ]
