# Generated by Django 5.2.3 on 2025-07-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0006_update_transcript_relationships'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='embedding_vector_id',
        ),
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='transcript_data',
        ),
    ]
