# Generated by Django 5.2.3 on 2025-07-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0007_optimize_transcript_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscript',
            name='language',
        ),
        migrations.AddField(
            model_name='videometadata',
            name='categories',
            field=models.JSONField(blank=True, default=list, help_text='YouTube categories'),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='channel_follower_count',
            field=models.BigIntegerField(blank=True, help_text='Channel subscriber count', null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='channel_id',
            field=models.CharField(blank=True, help_text='YouTube channel ID', max_length=50),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='channel_is_verified',
            field=models.BooleanField(default=False, help_text='Whether channel is verified'),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='language',
            field=models.CharField(default='en', help_text='Primary language of the video', max_length=10),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='like_count',
            field=models.BigIntegerField(blank=True, help_text='Number of likes', null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Video tags for categorization'),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Video thumbnail URL'),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='upload_date',
            field=models.DateField(blank=True, help_text='When video was published', null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='uploader_id',
            field=models.CharField(blank=True, help_text="Channel handle (e.g., '@TEDx')", max_length=100),
        ),
    ]
