# Generated by Django 5.2.3 on 2025-07-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0008_remove_videotranscript_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='Primary language of the video', max_length=10, null=True),
        ),
    ]
