# Generated by Django 5.2.3 on 2025-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0009_alter_videometadata_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='is_embedded',
            field=models.BooleanField(default=False, help_text='Whether video metadata has been embedded in vector store'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='key_points',
            field=models.JSONField(blank=True, default=list, help_text='List of key points extracted from the video'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the video content', null=True),
        ),
    ]
