# Generated by Django 5.2.3 on 2025-07-10 03:05

from django.db import migrations


def create_video_id_lookup_method(apps, schema_editor):
    """
    Data migration to populate video_id field in VideoTranscript with proper values.
    This allows us to use video_id as a lookup field without changing the primary key.
    """
    VideoTranscript = apps.get_model('video_processor', 'VideoTranscript')
    
    # Update video_id values to match their related VideoMetadata.video_id
    for transcript in VideoTranscript.objects.select_related('video_metadata'):
        if transcript.video_metadata and transcript.video_metadata.video_id:
            transcript.video_id = transcript.video_metadata.video_id
            transcript.save()
            print(f"Updated VideoTranscript {transcript.id} with video_id: {transcript.video_id}")


def reverse_video_id_lookup_method(apps, schema_editor):
    """
    Reverse migration - clear video_id values
    """
    VideoTranscript = apps.get_model('video_processor', 'VideoTranscript')
    VideoTranscript.objects.update(video_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0013_prepare_videotranscript_video_id_fk'),
    ]

    operations = [
        migrations.RunPython(
            create_video_id_lookup_method,
            reverse_video_id_lookup_method,
        ),
    ]