# Generated by Django 5.2.3 on 2025-07-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0014_update_videotranscript_video_id_lookup'),
    ]

    operations = [
        # Add index on VideoTranscript.video_id for efficient lookups
        migrations.AlterField(
            model_name='videotranscript',
            name='video_id',
            field=models.CharField(
                max_length=20,
                null=False,
                blank=False,
                db_index=True,  # Add database index
                unique=True,    # Ensure uniqueness
                help_text='YouTube video ID - natural key for lookups'
            ),
        ),
        
        # Add composite index on TranscriptSegment for efficient segment lookups
        migrations.AddIndex(
            model_name='transcriptsegment',
            index=models.Index(
                fields=['segment_id'],
                name='segment_id_idx'
            ),
        ),
        
        # URLRequestTable index will be added in the api app migration
    ]