# Generated by Django 5.2.3 on 2025-07-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_urlrequesttable_search_request_idx'),
        ('video_processor', '0015_add_natural_key_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transcriptsegment',
            name='segment_id_idx',
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['video_id'], name='video_proce_video_i_33baae_idx'),
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['status'], name='video_proce_status_bca4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['created_at'], name='video_proce_created_efffe2_idx'),
        ),
        migrations.AddIndex(
            model_name='videotranscript',
            index=models.Index(fields=['video_id'], name='video_proce_video_i_18512d_idx'),
        ),
        migrations.AddIndex(
            model_name='videotranscript',
            index=models.Index(fields=['status'], name='video_proce_status_efd541_idx'),
        ),
        migrations.AddIndex(
            model_name='videotranscript',
            index=models.Index(fields=['created_at'], name='video_proce_created_90199d_idx'),
        ),
    ]
