# Generated by Django 5.2.3 on 2025-07-10 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0016_remove_transcriptsegment_segment_id_idx_and_more'),
    ]

    operations = [
        # Step 1: Remove the auto-generated primary key
        migrations.RemoveField(
            model_name='videometadata',
            name='id',
        ),
        
        # Step 2: Make video_id the primary key
        migrations.AlterField(
            model_name='videometadata',
            name='video_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, help_text="YouTube video ID (e.g., 'dQw4w9WgXcQ')"),
        ),
        
        # Step 3: Update foreign key references in VideoTranscript
        migrations.AlterField(
            model_name='videotranscript',
            name='video_metadata',
            field=models.OneToOneField(
                to='video_processor.VideoMetadata',
                on_delete=models.CASCADE,
                related_name='video_transcript',
                null=True,
                blank=True,
                to_field='video_id'
            ),
        ),
    ]