# Generated by Django 5.2.3 on 2025-07-10 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0017_switch_videometadata_to_video_id_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='video_metadata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_transcript', to='video_processor.videometadata'),
        ),
    ]
