# Generated by Django 5.2.3 on 2025-07-10 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0018_alter_videotranscript_video_metadata'),
    ]

    operations = [
        # Step 1: Remove the auto-generated primary key
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='id',
        ),
        
        # Step 2: Make segment_id the primary key
        migrations.AlterField(
            model_name='transcriptsegment',
            name='segment_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, help_text="Unique segment ID format: 'video_id_segment_number' (e.g., 'dQw4w9WgXcQ_001')"),
        ),
    ]