# Generated by Django 5.2.3 on 2025-07-10 XX:XX

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0019_switch_transcriptsegment_to_segment_id_pk'),
    ]

    operations = [
        # Step 1: Remove the auto-generated primary key
        migrations.RemoveField(
            model_name='videotranscript',
            name='id',
        ),
        
        # Step 2: Make video_id the primary key
        migrations.AlterField(
            model_name='videotranscript',
            name='video_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, help_text='YouTube video ID - natural key for lookups'),
        ),
        
        # Step 3: Update TranscriptSegment foreign key to reference by video_id
        migrations.AlterField(
            model_name='transcriptsegment',
            name='transcript',
            field=models.ForeignKey(
                to='video_processor.VideoTranscript',
                on_delete=models.CASCADE,
                related_name='segments',
                to_field='video_id'
            ),
        ),
    ]