# Generated by Django 5.2.3 on 2025-07-10 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0020_switch_videotranscript_to_video_id_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptsegment',
            name='transcript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='video_processor.videotranscript'),
        ),
    ]
