# Generated by Django 5.2.3 on 2025-07-10 19:11

from django.db import migrations


def add_transcript_id_column(apps, schema_editor):
    """
    Add transcript_id column to TranscriptSegment table.
    This column stores the video_id that references the VideoTranscript.
    Note: The column may already exist if added manually, so we use IF NOT EXISTS.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE video_processor_transcriptsegment 
            ADD COLUMN IF NOT EXISTS transcript_id character varying(20);
        """)
        print("Added transcript_id column to TranscriptSegment table")


def remove_transcript_id_column(apps, schema_editor):
    """
    Remove transcript_id column from TranscriptSegment table.
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE video_processor_transcriptsegment 
            DROP COLUMN IF EXISTS transcript_id CASCADE;
        """)
        print("Removed transcript_id column from TranscriptSegment table")


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0023_remove_videotranscript_video_metadata'),
    ]

    operations = [
        migrations.RunPython(
            add_transcript_id_column,
            remove_transcript_id_column,
        ),
    ]
