# Generated by Django 5.2.3 on 2025-07-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0024_add_transcript_id_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscript',
            name='url_request',
        ),
    ]
