# Generated by Django 5.2.3 on 2025-07-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_urlrequesttable_search_request_idx'),
        ('video_processor', '0025_remove_videotranscript_url_request_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='videometadata',
            name='video_proce_video_i_33baae_idx',
        ),
        migrations.RemoveIndex(
            model_name='videotranscript',
            name='video_proce_video_i_18512d_idx',
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['channel_id'], name='video_proce_channel_189abd_idx'),
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['language'], name='video_proce_languag_721ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['is_embedded'], name='video_proce_is_embe_f1cd6d_idx'),
        ),
    ]
