# Generated by Django 5.2.4 on 2025-07-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0027_add_videotranscript_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotranscript',
            name='video_metadata',
            field=models.OneToOneField(help_text='Foreign key to VideoMetadata for proper cascading deletes', on_delete=django.db.models.deletion.CASCADE, related_name='video_transcript', to='video_processor.videometadata'),
        ),
    ]
