# Generated by Django 5.2.3 on 2025-07-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0028_alter_videotranscript_video_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='extraction_metadata',
            field=models.JSONField(default=dict, help_text='Metadata about the extraction process'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='transcript_source',
            field=models.CharField(choices=[('decodo', 'Decodo API'), ('youtube_api', 'YouTube Transcript API'), ('manual', 'Manual Upload')], default='decodo', help_text='Source used for transcript extraction', max_length=20),
        ),
    ]
