# Generated by Django 5.2.3 on 2025-07-18 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0029_add_transcript_source_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscript',
            name='extraction_metadata',
        ),
    ]
