# Generated by Django 5.2.3 on 2025-07-19 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_add_video_exclusion_table'),
        ('video_processor', '0030_remove_extraction_metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExclusionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text='YouTube video ID (extracted from URL)', max_length=20, unique=True)),
                ('video_url', models.URLField(help_text='Original YouTube video URL', max_length=500)),
                ('exclusion_reason', models.CharField(choices=[('privacy_restricted', 'Privacy Restricted'), ('language_unsupported', 'Language Not Supported'), ('content_unavailable', 'Content Unavailable'), ('duration_too_short', 'Duration Too Short'), ('duration_too_long', 'Duration Too Long'), ('transcript_unavailable', 'No Transcript Available'), ('unprocessable', 'Unprocessable')], help_text='Business reason why this video cannot be processed', max_length=30)),
                ('detected_at', models.DateTimeField(auto_now_add=True, help_text='When this exclusion was first detected')),
                ('detected_during_search', models.ForeignKey(blank=True, help_text='Search request that discovered this exclusion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='topic.searchrequest')),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['video_id'], name='video_proce_video_i_f7cbec_idx'), models.Index(fields=['exclusion_reason'], name='video_proce_exclusi_9bdbe2_idx'), models.Index(fields=['detected_at'], name='video_proce_detecte_081358_idx')],
            },
        ),
    ]
