# Generated by Django 5.2.3 on 2025-07-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0031_add_video_exclusion_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoexclusiontable',
            name='detected_during_search',
        ),
        migrations.AlterField(
            model_name='videoexclusiontable',
            name='exclusion_reason',
            field=models.CharField(choices=[('privacy_restricted', 'Privacy Restricted'), ('language_unsupported', 'Language Not Supported'), ('content_unavailable', 'Content Unavailable'), ('duration_too_short', 'Duration Too Short'), ('duration_too_long', 'Duration Too Long'), ('transcript_unavailable', 'No Transcript Available'), ('background_music_only', 'Background Music Only')], help_text='Business reason why this video cannot be processed', max_length=30),
        ),
    ]
