# Generated by Django 5.2.3 on 2025-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0032_refine_video_exclusion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videometadata',
            name='language',
            field=models.CharField(blank=True, default='en', help_text='Primary language of the video', max_length=12, null=True),
        ),
    ]
