# Generated by Django 5.2.3 on 2025-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_chain_task_id_field'),
        ('video_processor', '0033_expand_language_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='comment_count',
            field=models.BigIntegerField(blank=True, help_text='Number of comments', null=True),
        ),
        migrations.AddField(
            model_name='videometadata',
            name='engagement',
            field=models.JSONField(blank=True, default=list, help_text='High engagement segments (>95% from heatmap)'),
        ),
        migrations.AddIndex(
            model_name='videometadata',
            index=models.Index(fields=['comment_count'], name='video_proce_comment_8d109f_idx'),
        ),
    ]
