# Generated by Django 5.2.3 on 2025-08-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0034_add_engagement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='ad_duration_ratio',
            field=models.FloatField(blank=True, help_text='Total ad duration / video duration', null=True),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='ad_segments',
            field=models.JSONField(blank=True, default=list, help_text='[{"start": 30, "end": 60}, {"start": 240, "end": 270}]'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_analysis_preliminary',
            field=models.JSONField(blank=True, default=dict, help_text='{"ads": ["sponsor excerpt...", ...], "fillers": ["subscribe excerpt...", ...]}'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preliminary', 'Preliminary Complete'), ('failed', 'Analysis Failed'), ('final', 'Final Complete')], default='pending', help_text='Status of content analysis pipeline', max_length=20),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_rating',
            field=models.FloatField(blank=True, help_text='0.0-1.0 content quality rating (1 - ad_ratio - filler_ratio)', null=True),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='content_segments',
            field=models.JSONField(blank=True, default=list, help_text='[{"start": 15, "end": 30}, {"start": 60, "end": 240}]'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='filler_duration_ratio',
            field=models.FloatField(blank=True, help_text='Total filler duration / video duration', null=True),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='filler_segments',
            field=models.JSONField(blank=True, default=list, help_text='[{"start": 0, "end": 15}, {"start": 580, "end": 600}]'),
        ),
        migrations.AddField(
            model_name='videotranscript',
            name='speaker_tones',
            field=models.JSONField(blank=True, default=list, help_text="List of detected speaker tones: ['positive', 'informal', 'humorous']"),
        ),
    ]
