# Generated by Django 5.2.3 on 2025-08-04 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0035_add_content_analysis_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videotranscript',
            name='content_analysis_preliminary',
        ),
    ]
