# Generated by Django 5.2.3 on 2025-08-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0036_remove_content_analysis_preliminary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preliminary_analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of preliminary content analysis (ads/filler detection, tone analysis)', max_length=20)),
                ('speaker_tones', models.JSONField(blank=True, default=list, help_text="List of detected speaker tones: ['informal', 'positive', 'humorous']")),
                ('raw_ad_segments', models.JSONField(blank=True, default=list, help_text='Raw ad segments with text excerpts only: [{"text": "...", "description": "..."}]')),
                ('raw_filler_segments', models.JSONField(blank=True, default=list, help_text='Raw filler segments with text excerpts only: [{"text": "...", "description": "..."}]')),
                ('timestamped_analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of final timestamped analysis and ratio calculation', max_length=20)),
                ('content_rating', models.FloatField(blank=True, help_text='0.0-1.0 content quality rating (1 - ad_ratio - filler_ratio)', null=True)),
                ('ad_duration_ratio', models.FloatField(blank=True, help_text='Total ad duration / video duration', null=True)),
                ('filler_duration_ratio', models.FloatField(blank=True, help_text='Total filler duration / video duration', null=True)),
                ('ad_segments', models.JSONField(blank=True, default=list, help_text='Final ad segments with timestamps: [{"start": 30, "end": 60, "desc": "..."}]')),
                ('filler_segments', models.JSONField(blank=True, default=list, help_text='Final filler segments with timestamps: [{"start": 0, "end": 15, "desc": "..."}]')),
                ('content_segments', models.JSONField(blank=True, default=list, help_text='Final content segments with timestamps: [{"start": 15, "end": 30, "desc": "..."}]')),
                ('preliminary_completed_at', models.DateTimeField(blank=True, help_text='When preliminary analysis was completed', null=True)),
                ('final_completed_at', models.DateTimeField(blank=True, help_text='When final timestamped analysis was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content_analysis', to='video_processor.videotranscript')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['preliminary_analysis_status'], name='video_proce_prelimi_08f104_idx'), models.Index(fields=['timestamped_analysis_status'], name='video_proce_timesta_c9855b_idx'), models.Index(fields=['content_rating'], name='video_proce_content_a4f46c_idx'), models.Index(fields=['created_at'], name='video_proce_created_ba005f_idx')],
            },
        ),
    ]
