# Generated by Django 5.2.3 on 2025-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0038_migrate_existing_content_analysis'),
    ]

    operations = [
        # Remove old content analysis fields from VideoTranscript
        # Data has already been migrated to ContentAnalysis model in previous migration
        
        migrations.RemoveField(
            model_name='videotranscript',
            name='content_rating',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='speaker_tones',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='ad_segments',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='filler_segments',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='content_segments',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='ad_duration_ratio',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='filler_duration_ratio',
        ),
        migrations.RemoveField(
            model_name='videotranscript',
            name='content_analysis_status',
        ),
    ]
