# Generated by Django 5.2.3 on 2025-08-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0039_remove_old_content_analysis_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotranscript',
            name='chapters',
            field=models.JSONField(blank=True, default=list, help_text="List of chapters with one-line summaries: [{'chapter': int, 'title': str, 'summary': str}]"),
        ),
    ]
