# Generated by Django 5.2.3 on 2025-08-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_processor', '0040_videotranscript_chapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='videometadata',
            name='channel_thumbnail',
            field=models.URLField(blank=True, help_text='Channel avatar/thumbnail URL'),
        ),
    ]
