# Generated by Django 5.2.3 on 2025-07-08 13:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_ip', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='topic_searc_session_f06159_idx'), models.Index(fields=['user_ip'], name='topic_searc_user_ip_3737ab_idx'), models.Index(fields=['created_at'], name='topic_searc_created_567279_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('original_query', models.TextField(help_text="User's original query")),
                ('processed_query', models.TextField(blank=True, help_text='LLM-enhanced query for YouTube search')),
                ('video_urls', models.JSONField(blank=True, default=list, help_text='List of YouTube video URLs found')),
                ('total_videos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('failed', 'Failed'), ('success', 'Success')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status is failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('search_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to='topic.searchsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['request_id'], name='topic_searc_request_061e1d_idx'), models.Index(fields=['search_session', 'created_at'], name='topic_searc_search__f9feac_idx'), models.Index(fields=['status'], name='topic_searc_status_40d082_idx')],
            },
        ),
    ]
