# Generated by Django 5.2.3 on 2025-07-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_rename_request_id_to_search_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchrequest',
            new_name='topic_searc_search__b213fd_idx',
            old_name='topic_searc_search__search_id_idx',
        ),
    ]
