# Generated by Django 5.2.3 on 2025-07-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_add_video_exclusion_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('FACTUAL', 'Factual'), ('TUTORIAL', 'Tutorial'), ('REVIEW', 'Review'), ('HOW_TO', 'How To'), ('COMPARISON', 'Comparison')], help_text='Classified intent of the user query', max_length=20),
        ),
    ]
