# Generated by Django 5.2.3 on 2025-07-21 19:13

from django.db import migrations

def update_intent_categories(apps, schema_editor):
    """Update existing intent categories from old 5-category to new 4-category system"""
    SearchRequest = apps.get_model('topic', 'SearchRequest')
    
    # Mapping from old to new categories
    intent_mapping = {
        'FACTUAL': 'LOOKUP',      # FACTUAL becomes LOOKUP
        'COMPARISON': 'REVIEW',   # COMPARISON becomes REVIEW
        # TUTORIAL, HOW_TO, REVIEW stay the same
    }
    
    for old_intent, new_intent in intent_mapping.items():
        SearchRequest.objects.filter(intent_type=old_intent).update(intent_type=new_intent)

def reverse_intent_categories(apps, schema_editor):
    """Reverse the intent category changes"""
    SearchRequest = apps.get_model('topic', 'SearchRequest')
    
    # Reverse mapping (best effort - some data loss expected)
    reverse_mapping = {
        'LOOKUP': 'FACTUAL',
        'REVIEW': 'REVIEW',  # Some REVIEW might have been COMPARISON originally
    }
    
    for new_intent, old_intent in reverse_mapping.items():
        SearchRequest.objects.filter(intent_type=new_intent).update(intent_type=old_intent)


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_searchrequest_intent_type'),
    ]

    operations = [
        migrations.RunPython(update_intent_categories, reverse_intent_categories),
    ]
