# Generated by Django 5.2.3 on 2025-07-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0005_auto_20250721_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='processed_query',
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='concepts',
            field=models.JSONField(blank=True, default=list, help_text='List of concepts identified by LLM from the user query'),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='enhanced_queries',
            field=models.JSONField(blank=True, default=list, help_text='List of LLM-generated enhanced queries for search execution'),
        ),
        migrations.AlterField(
            model_name='searchrequest',
            name='intent_type',
            field=models.CharField(blank=True, choices=[('LOOKUP', 'Lookup'), ('TUTORIAL', 'Tutorial'), ('HOW_TO', 'How To'), ('REVIEW', 'Review')], help_text='Primary intent of the user query', max_length=20),
        ),
    ]
